version: "3.3"

services:
  curso_plugins_wp:
    build: .
    ports:
      - 80:80
      - 443:443
    environment:
      VIRTUAL_HOST: localhost
      WORDPRESS_DB_HOST: mariadb_10_5_5:3306
      WORDPRESS_DB_NAME: curso_plugins_wp
      WORDPRESS_DB_USER: curso_plugins_wp
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./public_html:/var/www/html
      - ./config.ini:/usr/local/etc/php/conf.d/config.ini
    container_name: curso_plugins_wp  

volumes:
  curso_plugins_wp:

networks:
  default:
    external:
      name: nginx-proxy
